{{- if .Values.ingress.enabled -}}
{{- $fullName := include "iipimage.fullname" . -}}
{{- range .Values.ingress.tls }}
{{- if .acme -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}-{{ .secretName }}
spec:
  acme:
    config:
    - domains:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      http01:
        ingressClass: nginx
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  secretName: {{ .secretName }}
{{- end }}
{{- end }}
{{- end }}