apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iipimage.fullname" . }}-node
  labels:
    {{- include "iipimage.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "iipimage.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Chart.Name }}-node
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "iipimage.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Chart.Name }}-node
    spec:
      containers:
      - name: {{ .Chart.Name }}-node
#        image: {{ template "iipimage.imagename" . }}
        image: ghcr.io/acdh-oeaw/jpeg2000-conversion-and-iiif-presentation/jp2-conv-iiif-pres
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.application.secretName }}
        envFrom:
        - secretRef:
            name: {{ .Values.application.secretName }}
{{- if .Values.extraEnvFrom }}
{{- toYaml .Values.extraEnvFrom | nindent 8 }}
{{- end }}
        {{- end }}
        env:
        - name: MEMCACHED_SERVERS
          value: {{ include "iipimage.fullname" . }}-memcached
# {{ .Values.image.tag }}
        ports:
        - containerPort: 3000
          name: node
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: image-data
          subPath: {{ kindIs "string" .Values.persistence.imageStorageSubPath | ternary .Values.persistence.imageStorageSubPath .Release.Name | quote }}
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - mkdir -p /data/upload/md5 && chown -R 100:82 /data/upload && chmod -R g+w /data/upload
        command:
        - /bin/sh
        - -c
        image: busybox
        imagePullPolicy: Always
        name: iipsrv-create-images
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: image-data
          subPath: {{ kindIs "string" .Values.persistence.imageStorageSubPath | ternary .Values.persistence.imageStorageSubPath .Release.Name | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: image-data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.imageStoragePVC }}