apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iipimage.fullname" . }}-node
  labels:
    {{- include "iipimage.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "iipimage.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "iipimage.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: node
    spec:
      containers:
      - env:
        - name: IIIF_DATA_PATH
          value: /data/forIIIF
        - name: IMAGE_DATA_PATH
          value: /data/upload
        - name: IMAGE_MD5_CHECKSUMS_PATH
          value: /data/upload/md5
        - name: MEMCACHED_SERVERS
          value: {{ include "iipimage.fullname" . }}-memcached
        - name: NO_VALIDATION_AT_STARTUP
          value: "true"
        - name: DEFAULT_COLLECTION
          value: "{{ .Values.iiifDefaultCollection }}"
        image: "acdhch/node-jp2:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name: node
        ports:
        - containerPort: 3000
          name: node
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: image-data
          subPath: {{ .Release.Name }}
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - mkdir -p /data/upload/md5 && chown -R 100:82 /data/upload && chmod -R g+w /data
        command:
        - /bin/sh
        - -c
        image: busybox
        imagePullPolicy: Always
        name: iipsrv-create-images
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: image-data
          subPath: {{ .Release.Name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: image-data
        persistentVolumeClaim:
          claimName: iiif-picture-storage