apiVersion: v1
kind: Service
metadata:
  name: {{ include "iipimage.fullname" . }}-rev-proxy
  labels:
    {{- include "iipimage.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-rev-proxy-svc
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "iipimage.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-rev-proxy
  type: ClusterIP
