apiVersion: v1
kind: Service
metadata:
  name: {{ include "iipimage.fullname" . }}-iipsrv
  labels:
    {{- include "iipimage.labels" . | nindent 4 }}
    app.kubernetes.io/component: iipsrv-svc
spec:
  ports:
  - name: iipsrv
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    {{- include "iipimage.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: iipsrv
  type: ClusterIP